[mypy]

# ------------------------------------------------------
# Python version
# ------------------------------------------------------
python_version = 3.10


# ------------------------------------------------------
# Basic behavior
# ------------------------------------------------------
warn_return_any = True
warn_unused_configs = True


# ------------------------------------------------------
# Gradual typing approach
# (strict enough to be useful,
# relaxed enough for ML projects)
# ------------------------------------------------------
disallow_untyped_defs = False
check_untyped_defs = True


# ------------------------------------------------------
# Ignore third-party libraries
# that do not ship type hints
# ------------------------------------------------------
ignore_missing_imports = True


# ------------------------------------------------------
# Exclude folders that are not
# production code
# ------------------------------------------------------
exclude = experiments|data|tests